services:
  zk-1:
    image: confluentinc/cp-zookeeper:${KAFKA_VERSION}
    hostname: zk-1
    container_name: zk-1
    restart: on-failure
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zk-1:2888:3888
    volumes:
      - "./volumes/zookeeper/data:/var/lib/zookeeper/data"
      - "./volumes/zookeeper/transactions:/var/lib/zookeeper/log"
    user: root
    networks:
      - ${GLOBAL_NETWORK}

  kafka-broker-1:
    image: confluentinc/cp-kafka:${KAFKA_VERSION}
    hostname: kafka-broker-1
    container_name: kafka-broker-1
    restart: on-failure
    volumes:
      - "./volumes/kafka/broker-1:/var/lib/kafka/data"
    depends_on:
      - zk-1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zk-1:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      # Listener configuration
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092

      # Other configuration
      KAFKA_LOG4J_LOGGERS: "kafka.authorizer.logger=INFO,kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms512M"
      KAFKA_COMPRESSION_TYPE: producer
      KAFKA_LOG4J_ROOT_LOGLEVEL: WARN

    user: root
    networks:
      - ${GLOBAL_NETWORK}